config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/:locale' => 'static_pages#home'
  scope '/:locale', locale: /#{I18n.available_locales.join("|")}/ do
    get 'datetime' => 'static_pages#datetime'
    get 'help' => 'static_pages#help'
    get 'privacy' => 'static_pages#privacy'
    get 'about' => 'static_pages#about'
    get 'contact' => 'static_pages#contact'
    get 'signup' => 'users#new'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets, only: %i[new create edit update]
    resources :projects, only: %i[index create update destroy]
    resources :tasks, only: %i[create update] do
      put :destroy, on: :collection
      put :complete, on: :member
      put :prioritize, on: :member
    end
  end
  get '/auth/:service/callback', to: 'services#create'
  resources :services, only: %i[index create destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :task, dependent: :delete_all
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project
  default_scope -> { order(position: :desc) }
  scope :recent_first, -> { order(created_at: :desc) }
  validates :name,:start_time, :end_time, presence: true
  validate :end_date_after_start_date


  private

  def end_date_after_start_date
    return if end_time.blank? || start_time.blank?

    errors.add(:end_time, 'must be after the start date') if end_time < start_time
    errors.add(:start_time, 'must be after the start date') if start_time > end_time
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task!, only: [:update, :prioritize, :complete]
  before_action :find_project!, only: [:create]
  include ActionView::Helpers::DateHelper
  def create
    @task = @project.task.create(task_params)

    if @task.save
      render json: { entry: render_to_string(partial: 'task', locals: { task: @task }), message: 'Задача создана'},
             status: 202

    else
      render json: {errors: @task.errors}, status: 422
    end
  end

  def destroy
    Task.where(id: params[:task][:task_ids]).destroy_all
    render nothing: true, status: 200
  end

  def complete
    @task.update(completed: !@task.completed)

    render nothing: true, status: 200
  end

  def update
    if @task.update(task_params)
      render json: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  def prioritize
    @task.insert_at(params[:position])

    render nothing: true, status: 200
  end

  private

  def task_params
    params.require(:task).permit(:name, :position, :start_time, :end_time)
  end

  def find_task!
    @task = Task.find(params[:id])
  end

  def find_project!
    @project = current_user.projects.find(params[:task][:project_id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.erb
<li class='task-item <%= "completed" if task.completed %>' id='task-item-<%= task.id%>'>
  <input type='checkbox' id='task-<%= task.id %>' name='task[task_ids][]' value='<%= task.id %>'/>
  <label class="toggle" for='task-<%= task.id %>'></label>
  <span class='task-name' id='task-<%= task.id %>' data-original-title="<%= t('tasks.name') %>" data-model="task" data-resource='task' data-name='name' data-url='<%= task_path(task) %>'>
    <%= task.name %>
  </span>
  <div class='pull-right task-options'>
    <%= link_to '#', class: 'edit-start-time', id: "edit-start-time-#{task.id}", title: 'Дата начала задачи',pk: task.id do %>
      <%= t('tasks.start') %>
    <% end %>
    <span class='edit-start-time' id='edit-start-time-<%= task.id %>' data-original-title="<%= t('tasks.date_start') %>" data-id="<%= task.id %>"  data-date="<%= task.end_time %>" data-model="task" data-resource='task' data-name='start_time' data-url='<%= task_path(task) %>' data-type="date">
      <%= task.start_time&.strftime('%d.%m.%Y') %>
    </span> |
    <%= link_to '#', class: 'edit-end-time', id: "edit-end-time-#{task.id}", title: 'Дата окончания задачи',pk: task.id do %>
      <%= t('tasks.end') %>
    <% end %>
    <span class='edit-end-time' id='edit-end-time-<%= task.id %>' data-original-title="<%= t('tasks.date_end') %>" data-id="<%= task.id %>" data-date="<%= task.end_time %>" data-completed="<%= task.completed %>" data-model="task" data-resource='task' data-name='end_time' data-url='<%= task_path(task) %>' data-type="date">
      <%= task.end_time&.strftime('%d.%m.%Y') %>
    </span> |
    <%= link_to complete_task_path(task), remote: true, method: 'put', class: 'complete-task', title: task.completed?? t('tasks.mark.not_completed') : t('tasks.mark.completed') do %>
      <%= icon_label task.completed?? 'icon-thumbs-down' : 'icon-thumbs-up' %>
    <% end %>
    <%= link_to '#', id: "edit-task-name-#{task.id}", class: 'edit-task-name', title: t('tasks.edit') do %>
      <%= icon_label 'icon-pencil' %>
    <% end %>
    <%= icon_label 'icon-resize-vertical task-drag-handle' %>
  </div>
</li>