config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/:locale' => 'static_pages#home'
  scope '/:locale', locale: /#{I18n.available_locales.join("|")}/ do
    get 'datetime' => 'static_pages#datetime'
    get 'help' => 'static_pages#help'
    get 'privacy' => 'static_pages#privacy'
    get 'about' => 'static_pages#about'
    get 'contact' => 'static_pages#contact'
    get 'signup' => 'users#new'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets, only: %i[new create edit update]
    resources :projects, only: %i[index create update destroy]
    resources :tasks, only: %i[create update] do
      put :destroy, on: :collection
      put :complete, on: :member
      put :prioritize, on: :member
    end
  end
  get '/auth/:service/callback', to: 'services#create'
  resources :services, only: %i[index create destroy]
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small blue">


  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://www.linkedin.com/in/denis-dikiy-604529192">DDA</a>
  </div>


</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t('menu.text_logo'), root_path, id: "logo" %>
    <nav class="navbar-expand-lg">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('menu.home'), root_path %></li>
        <% if logged_in? %>
          <li><%= link_to t('menu.users'), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('menu.account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('menu.profile'), current_user %></li>
              <li><%= link_to t('menu.settings'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('menu.log_out'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('menu.log_in'), login_path %></li>
        <% end %>
        <div class="language">
          <% if I18n.locale == I18n.default_locale %>
            <li><%= link_to "Ru", {:locale => 'ru'}, class: 'nav-link disabled' %></li>
            <li class="divider">|</li>
            <li><%= link_to "En", {:locale => 'en'} %></li>
          <% else %>
            <li><%= link_to "Ru", {:locale => 'ru'} %></li>
            <li class="divider">|</li>
            <li><%= link_to "En", {:locale => 'en'}, class: 'nav-link disabled' %></li>
          <% end %>
        </div>
      </ul>

    </nav>


  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body id='<%= controller_path.dasherize.gsub('/', '-') %>' data-action='<%= action_name.dasherize %>' data-locale="<%= I18n.locale %>">
<%= render 'layouts/header' %>
<div id='wrapper'>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div id='main-content' class='container'>
    <%= yield %>
    <div id='push'></div>
  </div>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>